# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transmit.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/protobuf/duration_pb'


descriptor_data = "\n\x0etransmit.proto\x12\x08transmit\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xcd\x01\n\x1bScheduleTransmissionRequest\x12$\n\x07\x64\x65layed\x18\x01 \x01(\x0b\x32\x11.transmit.DelayedH\x00\x12&\n\x08interval\x18\x02 \x01(\x0b\x32\x12.transmit.IntervalH\x00\x12\x1e\n\x04\x63ron\x18\x03 \x01(\x0b\x32\x0e.transmit.CronH\x00\x12)\n\nnats_event\x18\x04 \x01(\x0b\x32\x13.transmit.NatsEventH\x01\x42\n\n\x08ScheduleB\t\n\x07Message\"7\n\x1cScheduleTransmissionResponse\x12\x17\n\x0ftransmission_id\x18\x01 \x01(\t\"-\n\tNatsEvent\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\":\n\x07\x44\x65layed\x12/\n\x0btransmit_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa1\x01\n\x08Interval\x12\x36\n\x12\x66irst_transmission\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x08interval\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x0f\n\x05times\x18\x03 \x01(\rH\x00\x12\x14\n\ninfinitely\x18\x04 \x01(\x08H\x00\x42\t\n\x07Iterate\"\x88\x01\n\x04\x43ron\x12<\n\x18\x66irst_transmission_after\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08schedule\x18\x02 \x01(\t\x12\x0f\n\x05times\x18\x03 \x01(\rH\x00\x12\x14\n\ninfinitely\x18\x04 \x01(\x08H\x00\x42\t\n\x07Iterate\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa3\x01\n\x13HealthCheckResponse\x12;\n\x06status\x18\x01 \x01(\x0e\x32+.transmit.HealthCheckResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\x32q\n\x08Transmit\x12\x65\n\x14ScheduleTransmission\x12%.transmit.ScheduleTransmissionRequest\x1a&.transmit.ScheduleTransmissionResponse2\x96\x01\n\x06Health\x12\x44\n\x05\x43heck\x12\x1c.transmit.HealthCheckRequest\x1a\x1d.transmit.HealthCheckResponse\x12\x46\n\x05Watch\x12\x1c.transmit.HealthCheckRequest\x1a\x1d.transmit.HealthCheckResponse0\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.protobuf.Timestamp", "google/protobuf/timestamp.proto"],
    ["google.protobuf.Duration", "google/protobuf/duration.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Transmit
  ScheduleTransmissionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transmit.ScheduleTransmissionRequest").msgclass
  ScheduleTransmissionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transmit.ScheduleTransmissionResponse").msgclass
  NatsEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transmit.NatsEvent").msgclass
  Delayed = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transmit.Delayed").msgclass
  Interval = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transmit.Interval").msgclass
  Cron = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transmit.Cron").msgclass
  HealthCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transmit.HealthCheckRequest").msgclass
  HealthCheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transmit.HealthCheckResponse").msgclass
  HealthCheckResponse::ServingStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transmit.HealthCheckResponse.ServingStatus").enummodule
end
