<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transmit.proto

namespace Transmit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transmit.Delayed</code>
 */
class Delayed extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp transmit_at = 1;</code>
     */
    protected $transmit_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $transmit_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transmit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp transmit_at = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTransmitAt()
    {
        return $this->transmit_at;
    }

    public function hasTransmitAt()
    {
        return isset($this->transmit_at);
    }

    public function clearTransmitAt()
    {
        unset($this->transmit_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp transmit_at = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTransmitAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->transmit_at = $var;

        return $this;
    }

}

