<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transmit.proto

namespace Transmit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transmit.Interval</code>
 */
class Interval extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp first_transmission = 1;</code>
     */
    protected $first_transmission = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration interval = 2;</code>
     */
    protected $interval = null;
    protected $Iterate;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $first_transmission
     *     @type \Google\Protobuf\Duration $interval
     *     @type int $times
     *     @type bool $infinitely
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transmit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp first_transmission = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getFirstTransmission()
    {
        return $this->first_transmission;
    }

    public function hasFirstTransmission()
    {
        return isset($this->first_transmission);
    }

    public function clearFirstTransmission()
    {
        unset($this->first_transmission);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp first_transmission = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setFirstTransmission($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->first_transmission = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration interval = 2;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getInterval()
    {
        return $this->interval;
    }

    public function hasInterval()
    {
        return isset($this->interval);
    }

    public function clearInterval()
    {
        unset($this->interval);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration interval = 2;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setInterval($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->interval = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 times = 3;</code>
     * @return int
     */
    public function getTimes()
    {
        return $this->readOneof(3);
    }

    public function hasTimes()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>uint32 times = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTimes($var)
    {
        GPBUtil::checkUint32($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool infinitely = 4;</code>
     * @return bool
     */
    public function getInfinitely()
    {
        return $this->readOneof(4);
    }

    public function hasInfinitely()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>bool infinitely = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setInfinitely($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getIterate()
    {
        return $this->whichOneof("Iterate");
    }

}

