<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transmit.proto

namespace Transmit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transmit.ScheduleTransmissionResponse</code>
 */
class ScheduleTransmissionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string transmission_id = 1;</code>
     */
    protected $transmission_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transmission_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transmit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string transmission_id = 1;</code>
     * @return string
     */
    public function getTransmissionId()
    {
        return $this->transmission_id;
    }

    /**
     * Generated from protobuf field <code>string transmission_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTransmissionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transmission_id = $var;

        return $this;
    }

}

