// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: transmit.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package transmit;

@kotlin.jvm.JvmName("-initializehealthCheckResponse")
public inline fun healthCheckResponse(block: transmit.HealthCheckResponseKt.Dsl.() -> kotlin.Unit): transmit.TransmitOuterClass.HealthCheckResponse =
  transmit.HealthCheckResponseKt.Dsl._create(transmit.TransmitOuterClass.HealthCheckResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `transmit.HealthCheckResponse`
 */
public object HealthCheckResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: transmit.TransmitOuterClass.HealthCheckResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: transmit.TransmitOuterClass.HealthCheckResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): transmit.TransmitOuterClass.HealthCheckResponse = _builder.build()

    /**
     * `.transmit.HealthCheckResponse.ServingStatus status = 1;`
     */
    public var status: transmit.TransmitOuterClass.HealthCheckResponse.ServingStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * `.transmit.HealthCheckResponse.ServingStatus status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun transmit.TransmitOuterClass.HealthCheckResponse.copy(block: `transmit`.HealthCheckResponseKt.Dsl.() -> kotlin.Unit): transmit.TransmitOuterClass.HealthCheckResponse =
  `transmit`.HealthCheckResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

